version: "3.8"

services:
  api:
    build: ./app
    container_name: hr-api
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgresql123@host.docker.internal:5432/hr_reco

  dashboard:
    build: ./dashboard
    container_name: hr-dashboard
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000